### YamlMime:ManagedReference
items:
- uid: NeerCore.Application.Abstractions.ICommand`1
  commentId: T:NeerCore.Application.Abstractions.ICommand`1
  id: ICommand`1
  parent: NeerCore.Application.Abstractions
  children: []
  langs:
  - csharp
  - vb
  name: ICommand<TResponse>
  nameWithType: ICommand<TResponse>
  fullName: NeerCore.Application.Abstractions.ICommand<TResponse>
  type: Interface
  source:
    remote:
      path: src/NeerCore.Application.MediatR/Abstractions/ICommand.cs
      branch: v2.0.0
      repo: https://github.com/NeerSpace/NeerCore.git
    id: ICommand
    path: ../src/NeerCore.Application.MediatR/Abstractions/ICommand.cs
    startLine: 4
  assemblies:
  - NeerCore.Application.MediatR
  namespace: NeerCore.Application.Abstractions
  syntax:
    content: public interface ICommand<out TResponse>
    typeParameters:
    - id: TResponse
    content.vb: >-
      Public Interface ICommand(Of Out TResponse)
          Inherits IRequest(Of TResponse)
  nameWithType.vb: ICommand(Of TResponse)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
  fullName.vb: NeerCore.Application.Abstractions.ICommand(Of TResponse)
  name.vb: ICommand(Of TResponse)
references:
- uid: NeerCore.Application.Abstractions
  commentId: N:NeerCore.Application.Abstractions
  name: NeerCore.Application.Abstractions
  nameWithType: NeerCore.Application.Abstractions
  fullName: NeerCore.Application.Abstractions
