### YamlMime:ManagedReference
items:
- uid: NeerCore.Application.Abstractions.ICommand
  commentId: T:NeerCore.Application.Abstractions.ICommand
  id: ICommand
  parent: NeerCore.Application.Abstractions
  children: []
  langs:
  - csharp
  - vb
  name: ICommand
  nameWithType: ICommand
  fullName: NeerCore.Application.Abstractions.ICommand
  type: Interface
  source:
    remote:
      path: src/NeerCore.Application.MediatR/Abstractions/ICommand.cs
      branch: v2.0.0
      repo: https://github.com/NeerSpace/NeerCore.git
    id: ICommand
    path: ../src/NeerCore.Application.MediatR/Abstractions/ICommand.cs
    startLine: 6
  assemblies:
  - NeerCore.Application.MediatR
  namespace: NeerCore.Application.Abstractions
  syntax:
    content: 'public interface ICommand : ICommand<Unit>'
    content.vb: >-
      Public Interface ICommand
          Inherits ICommand(Of Unit)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
references:
- uid: NeerCore.Application.Abstractions
  commentId: N:NeerCore.Application.Abstractions
  name: NeerCore.Application.Abstractions
  nameWithType: NeerCore.Application.Abstractions
  fullName: NeerCore.Application.Abstractions
