### YamlMime:ManagedReference
items:
- uid: NeerCore.Api.Middleware.NeerSwaggerUIMiddleware
  commentId: T:NeerCore.Api.Middleware.NeerSwaggerUIMiddleware
  id: NeerSwaggerUIMiddleware
  parent: NeerCore.Api.Middleware
  children:
  - NeerCore.Api.Middleware.NeerSwaggerUIMiddleware.#ctor(RequestDelegate,IWebHostEnvironment,ILoggerFactory,System.Nullable{SwaggerUIOptions},IOptions{NeerCore.Api.Swagger.SwaggerConfigurationOptions})
  - NeerCore.Api.Middleware.NeerSwaggerUIMiddleware.Invoke(HttpContext)
  langs:
  - csharp
  - vb
  name: NeerSwaggerUIMiddleware
  nameWithType: NeerSwaggerUIMiddleware
  fullName: NeerCore.Api.Middleware.NeerSwaggerUIMiddleware
  type: Class
  source:
    remote:
      path: src/NeerCore.Api/Middleware/NeerSwaggerUIMiddleware.cs
      branch: v2.0.0
      repo: https://github.com/NeerSpace/NeerCore.git
    id: NeerSwaggerUIMiddleware
    path: ../src/NeerCore.Api/Middleware/NeerSwaggerUIMiddleware.cs
    startLine: 17
  assemblies:
  - NeerCore.Api
  namespace: NeerCore.Api.Middleware
  syntax:
    content: 'public class NeerSwaggerUIMiddleware : object'
    content.vb: >-
      Public Class NeerSwaggerUIMiddleware
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: NeerCore.Api.Middleware.NeerSwaggerUIMiddleware.#ctor(RequestDelegate,IWebHostEnvironment,ILoggerFactory,System.Nullable{SwaggerUIOptions},IOptions{NeerCore.Api.Swagger.SwaggerConfigurationOptions})
  commentId: M:NeerCore.Api.Middleware.NeerSwaggerUIMiddleware.#ctor(RequestDelegate,IWebHostEnvironment,ILoggerFactory,System.Nullable{SwaggerUIOptions},IOptions{NeerCore.Api.Swagger.SwaggerConfigurationOptions})
  id: '#ctor(RequestDelegate,IWebHostEnvironment,ILoggerFactory,System.Nullable{SwaggerUIOptions},IOptions{NeerCore.Api.Swagger.SwaggerConfigurationOptions})'
  parent: NeerCore.Api.Middleware.NeerSwaggerUIMiddleware
  langs:
  - csharp
  - vb
  name: NeerSwaggerUIMiddleware(RequestDelegate, IWebHostEnvironment, ILoggerFactory, Nullable<SwaggerUIOptions>, IOptions<SwaggerConfigurationOptions>)
  nameWithType: NeerSwaggerUIMiddleware.NeerSwaggerUIMiddleware(RequestDelegate, IWebHostEnvironment, ILoggerFactory, Nullable<SwaggerUIOptions>, IOptions<SwaggerConfigurationOptions>)
  fullName: NeerCore.Api.Middleware.NeerSwaggerUIMiddleware.NeerSwaggerUIMiddleware(RequestDelegate, IWebHostEnvironment, ILoggerFactory, System.Nullable<SwaggerUIOptions>, IOptions<NeerCore.Api.Swagger.SwaggerConfigurationOptions>)
  type: Constructor
  source:
    remote:
      path: src/NeerCore.Api/Middleware/NeerSwaggerUIMiddleware.cs
      branch: v2.0.0
      repo: https://github.com/NeerSpace/NeerCore.git
    id: .ctor
    path: ../src/NeerCore.Api/Middleware/NeerSwaggerUIMiddleware.cs
    startLine: 29
  assemblies:
  - NeerCore.Api
  namespace: NeerCore.Api.Middleware
  syntax:
    content: public NeerSwaggerUIMiddleware(RequestDelegate next, IWebHostEnvironment environment, ILoggerFactory loggerFactory, SwaggerUIOptions? options, IOptions<SwaggerConfigurationOptions> swaggerOptionsAccessor)
    parameters:
    - id: next
      type: RequestDelegate
    - id: environment
      type: IWebHostEnvironment
    - id: loggerFactory
      type: ILoggerFactory
    - id: options
      type: System.Nullable{SwaggerUIOptions}
    - id: swaggerOptionsAccessor
      type: IOptions{NeerCore.Api.Swagger.SwaggerConfigurationOptions}
    content.vb: Public Sub New(next As RequestDelegate, environment As IWebHostEnvironment, loggerFactory As ILoggerFactory, options As SwaggerUIOptions?, swaggerOptionsAccessor As IOptions(Of SwaggerConfigurationOptions))
  overload: NeerCore.Api.Middleware.NeerSwaggerUIMiddleware.#ctor*
  nameWithType.vb: NeerSwaggerUIMiddleware.NeerSwaggerUIMiddleware(RequestDelegate, IWebHostEnvironment, ILoggerFactory, Nullable(Of SwaggerUIOptions), IOptions(Of SwaggerConfigurationOptions))
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: NeerCore.Api.Middleware.NeerSwaggerUIMiddleware.NeerSwaggerUIMiddleware(RequestDelegate, IWebHostEnvironment, ILoggerFactory, System.Nullable(Of SwaggerUIOptions), IOptions(Of NeerCore.Api.Swagger.SwaggerConfigurationOptions))
  name.vb: NeerSwaggerUIMiddleware(RequestDelegate, IWebHostEnvironment, ILoggerFactory, Nullable(Of SwaggerUIOptions), IOptions(Of SwaggerConfigurationOptions))
- uid: NeerCore.Api.Middleware.NeerSwaggerUIMiddleware.Invoke(HttpContext)
  commentId: M:NeerCore.Api.Middleware.NeerSwaggerUIMiddleware.Invoke(HttpContext)
  id: Invoke(HttpContext)
  parent: NeerCore.Api.Middleware.NeerSwaggerUIMiddleware
  langs:
  - csharp
  - vb
  name: Invoke(HttpContext)
  nameWithType: NeerSwaggerUIMiddleware.Invoke(HttpContext)
  fullName: NeerCore.Api.Middleware.NeerSwaggerUIMiddleware.Invoke(HttpContext)
  type: Method
  source:
    remote:
      path: src/NeerCore.Api/Middleware/NeerSwaggerUIMiddleware.cs
      branch: v2.0.0
      repo: https://github.com/NeerSpace/NeerCore.git
    id: Invoke
    path: ../src/NeerCore.Api/Middleware/NeerSwaggerUIMiddleware.cs
    startLine: 45
  assemblies:
  - NeerCore.Api
  namespace: NeerCore.Api.Middleware
  syntax:
    content: public async Task Invoke(HttpContext httpContext)
    parameters:
    - id: httpContext
      type: HttpContext
    return:
      type: Task
    content.vb: Public Function Invoke(httpContext As HttpContext) As Task
  overload: NeerCore.Api.Middleware.NeerSwaggerUIMiddleware.Invoke*
  modifiers.csharp:
  - public
  - async
  modifiers.vb:
  - Public
references:
- uid: NeerCore.Api.Middleware
  commentId: N:NeerCore.Api.Middleware
  name: NeerCore.Api.Middleware
  nameWithType: NeerCore.Api.Middleware
  fullName: NeerCore.Api.Middleware
- uid: NeerCore.Api.Middleware.NeerSwaggerUIMiddleware.#ctor*
  commentId: Overload:NeerCore.Api.Middleware.NeerSwaggerUIMiddleware.#ctor
  name: NeerSwaggerUIMiddleware
  nameWithType: NeerSwaggerUIMiddleware.NeerSwaggerUIMiddleware
  fullName: NeerCore.Api.Middleware.NeerSwaggerUIMiddleware.NeerSwaggerUIMiddleware
- uid: RequestDelegate
  isExternal: true
  name: RequestDelegate
  nameWithType: RequestDelegate
  fullName: RequestDelegate
- uid: IWebHostEnvironment
  commentId: '!:IWebHostEnvironment'
  isExternal: true
  name: IWebHostEnvironment
  nameWithType: IWebHostEnvironment
  fullName: IWebHostEnvironment
- uid: ILoggerFactory
  isExternal: true
  name: ILoggerFactory
  nameWithType: ILoggerFactory
  fullName: ILoggerFactory
- uid: System.Nullable{SwaggerUIOptions}
  commentId: '!:System.Nullable{SwaggerUIOptions}'
  definition: System.Nullable`1
  name: Nullable<SwaggerUIOptions>
  nameWithType: Nullable<SwaggerUIOptions>
  fullName: System.Nullable<SwaggerUIOptions>
  nameWithType.vb: Nullable(Of SwaggerUIOptions)
  fullName.vb: System.Nullable(Of SwaggerUIOptions)
  name.vb: Nullable(Of SwaggerUIOptions)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: SwaggerUIOptions
    name: SwaggerUIOptions
    nameWithType: SwaggerUIOptions
    fullName: SwaggerUIOptions
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: SwaggerUIOptions
    name: SwaggerUIOptions
    nameWithType: SwaggerUIOptions
    fullName: SwaggerUIOptions
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: IOptions{NeerCore.Api.Swagger.SwaggerConfigurationOptions}
  commentId: '!:IOptions{NeerCore.Api.Swagger.SwaggerConfigurationOptions}'
  definition: IOptions`1
  name: IOptions<SwaggerConfigurationOptions>
  nameWithType: IOptions<SwaggerConfigurationOptions>
  fullName: IOptions<NeerCore.Api.Swagger.SwaggerConfigurationOptions>
  nameWithType.vb: IOptions(Of SwaggerConfigurationOptions)
  fullName.vb: IOptions(Of NeerCore.Api.Swagger.SwaggerConfigurationOptions)
  name.vb: IOptions(Of SwaggerConfigurationOptions)
  spec.csharp:
  - uid: IOptions`1
    name: IOptions
    nameWithType: IOptions
    fullName: IOptions
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: NeerCore.Api.Swagger.SwaggerConfigurationOptions
    name: SwaggerConfigurationOptions
    nameWithType: SwaggerConfigurationOptions
    fullName: NeerCore.Api.Swagger.SwaggerConfigurationOptions
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: IOptions`1
    name: IOptions
    nameWithType: IOptions
    fullName: IOptions
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: NeerCore.Api.Swagger.SwaggerConfigurationOptions
    name: SwaggerConfigurationOptions
    nameWithType: SwaggerConfigurationOptions
    fullName: NeerCore.Api.Swagger.SwaggerConfigurationOptions
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Nullable`1
  isExternal: true
  name: Nullable<>
  nameWithType: Nullable<>
  fullName: System.Nullable<>
  nameWithType.vb: Nullable(Of )
  fullName.vb: System.Nullable(Of )
  name.vb: Nullable(Of )
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: IOptions`1
  isExternal: true
  name: IOptions<>
  nameWithType: IOptions<>
  fullName: IOptions<>
  nameWithType.vb: IOptions(Of )
  fullName.vb: IOptions(Of )
  name.vb: IOptions(Of )
  spec.csharp:
  - uid: IOptions`1
    name: IOptions
    nameWithType: IOptions
    fullName: IOptions
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: IOptions`1
    name: IOptions
    nameWithType: IOptions
    fullName: IOptions
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: NeerCore.Api.Middleware.NeerSwaggerUIMiddleware.Invoke*
  commentId: Overload:NeerCore.Api.Middleware.NeerSwaggerUIMiddleware.Invoke
  name: Invoke
  nameWithType: NeerSwaggerUIMiddleware.Invoke
  fullName: NeerCore.Api.Middleware.NeerSwaggerUIMiddleware.Invoke
- uid: HttpContext
  isExternal: true
  name: HttpContext
  nameWithType: HttpContext
  fullName: HttpContext
- uid: Task
  isExternal: true
  name: Task
  nameWithType: Task
  fullName: Task
