### YamlMime:ManagedReference
items:
- uid: NeerCore.Api.DefaultRoutes
  commentId: T:NeerCore.Api.DefaultRoutes
  id: DefaultRoutes
  parent: NeerCore.Api
  children:
  - NeerCore.Api.DefaultRoutes.LocalizedRoute
  - NeerCore.Api.DefaultRoutes.VersionedRoute
  langs:
  - csharp
  - vb
  name: DefaultRoutes
  nameWithType: DefaultRoutes
  fullName: NeerCore.Api.DefaultRoutes
  type: Class
  source:
    remote:
      path: src/NeerCore.Api/DefaultRoutes.cs
      branch: v2.0.0
      repo: https://github.com/NeerSpace/NeerCore.git
    id: DefaultRoutes
    path: ../src/NeerCore.Api/DefaultRoutes.cs
    startLine: 2
  assemblies:
  - NeerCore.Api
  namespace: NeerCore.Api
  syntax:
    content: 'public static class DefaultRoutes : object'
    content.vb: >-
      Public Module DefaultRoutes
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: NeerCore.Api.DefaultRoutes.VersionedRoute
  commentId: F:NeerCore.Api.DefaultRoutes.VersionedRoute
  id: VersionedRoute
  parent: NeerCore.Api.DefaultRoutes
  langs:
  - csharp
  - vb
  name: VersionedRoute
  nameWithType: DefaultRoutes.VersionedRoute
  fullName: NeerCore.Api.DefaultRoutes.VersionedRoute
  type: Field
  source:
    remote:
      path: src/NeerCore.Api/DefaultRoutes.cs
      branch: v2.0.0
      repo: https://github.com/NeerSpace/NeerCore.git
    id: VersionedRoute
    path: ../src/NeerCore.Api/DefaultRoutes.cs
    startLine: 4
  assemblies:
  - NeerCore.Api
  namespace: NeerCore.Api
  syntax:
    content: public const string VersionedRoute = null
    return:
      type: System.String
    content.vb: Public Const VersionedRoute As String = Nothing
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: NeerCore.Api.DefaultRoutes.LocalizedRoute
  commentId: F:NeerCore.Api.DefaultRoutes.LocalizedRoute
  id: LocalizedRoute
  parent: NeerCore.Api.DefaultRoutes
  langs:
  - csharp
  - vb
  name: LocalizedRoute
  nameWithType: DefaultRoutes.LocalizedRoute
  fullName: NeerCore.Api.DefaultRoutes.LocalizedRoute
  type: Field
  source:
    remote:
      path: src/NeerCore.Api/DefaultRoutes.cs
      branch: v2.0.0
      repo: https://github.com/NeerSpace/NeerCore.git
    id: LocalizedRoute
    path: ../src/NeerCore.Api/DefaultRoutes.cs
    startLine: 5
  assemblies:
  - NeerCore.Api
  namespace: NeerCore.Api
  syntax:
    content: public const string LocalizedRoute = null
    return:
      type: System.String
    content.vb: Public Const LocalizedRoute As String = Nothing
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: NeerCore.Api
  commentId: N:NeerCore.Api
  name: NeerCore.Api
  nameWithType: NeerCore.Api
  fullName: NeerCore.Api
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
