### YamlMime:ManagedReference
items:
- uid: NeerCore.Api.Swagger
  commentId: N:NeerCore.Api.Swagger
  id: NeerCore.Api.Swagger
  children:
  - NeerCore.Api.Swagger.SwaggerConfigurationOptions
  - NeerCore.Api.Swagger.SwaggerSecurityOptions
  langs:
  - csharp
  - vb
  name: NeerCore.Api.Swagger
  nameWithType: NeerCore.Api.Swagger
  fullName: NeerCore.Api.Swagger
  type: Namespace
  assemblies:
  - NeerCore.Api
references:
- uid: NeerCore.Api.Swagger.SwaggerConfigurationOptions
  commentId: T:NeerCore.Api.Swagger.SwaggerConfigurationOptions
  parent: NeerCore.Api.Swagger
  name: SwaggerConfigurationOptions
  nameWithType: SwaggerConfigurationOptions
  fullName: NeerCore.Api.Swagger.SwaggerConfigurationOptions
- uid: NeerCore.Api.Swagger.SwaggerSecurityOptions
  commentId: T:NeerCore.Api.Swagger.SwaggerSecurityOptions
  parent: NeerCore.Api.Swagger
  name: SwaggerSecurityOptions
  nameWithType: SwaggerSecurityOptions
  fullName: NeerCore.Api.Swagger.SwaggerSecurityOptions
- uid: NeerCore.Api.Swagger
  commentId: N:NeerCore.Api.Swagger
  name: NeerCore.Api.Swagger
  nameWithType: NeerCore.Api.Swagger
  fullName: NeerCore.Api.Swagger
