### YamlMime:ManagedReference
items:
- uid: NeerCore.Api.Swagger.Filters.XLogoDocumentFilter
  commentId: T:NeerCore.Api.Swagger.Filters.XLogoDocumentFilter
  id: XLogoDocumentFilter
  parent: NeerCore.Api.Swagger.Filters
  children:
  - NeerCore.Api.Swagger.Filters.XLogoDocumentFilter.Apply(OpenApiDocument,DocumentFilterContext)
  langs:
  - csharp
  - vb
  name: XLogoDocumentFilter
  nameWithType: XLogoDocumentFilter
  fullName: NeerCore.Api.Swagger.Filters.XLogoDocumentFilter
  type: Class
  source:
    remote:
      path: src/NeerCore.Api/Swagger/Filters/XLogoDocumentFilter.cs
      branch: v2.0.0
      repo: https://github.com/NeerSpace/NeerCore.git
    id: XLogoDocumentFilter
    path: ../src/NeerCore.Api/Swagger/Filters/XLogoDocumentFilter.cs
    startLine: 9
  assemblies:
  - NeerCore.Api
  namespace: NeerCore.Api.Swagger.Filters
  summary: "\nSwagger document filter to show NeerCore logo in ReDoc.\n"
  example: []
  syntax:
    content: 'public sealed class XLogoDocumentFilter : IDocumentFilter'
    content.vb: >-
      Public NotInheritable Class XLogoDocumentFilter
          Inherits IDocumentFilter
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: NeerCore.Api.Swagger.Filters.XLogoDocumentFilter.Apply(OpenApiDocument,DocumentFilterContext)
  commentId: M:NeerCore.Api.Swagger.Filters.XLogoDocumentFilter.Apply(OpenApiDocument,DocumentFilterContext)
  id: Apply(OpenApiDocument,DocumentFilterContext)
  parent: NeerCore.Api.Swagger.Filters.XLogoDocumentFilter
  langs:
  - csharp
  - vb
  name: Apply(OpenApiDocument, DocumentFilterContext)
  nameWithType: XLogoDocumentFilter.Apply(OpenApiDocument, DocumentFilterContext)
  fullName: NeerCore.Api.Swagger.Filters.XLogoDocumentFilter.Apply(OpenApiDocument, DocumentFilterContext)
  type: Method
  source:
    remote:
      path: src/NeerCore.Api/Swagger/Filters/XLogoDocumentFilter.cs
      branch: v2.0.0
      repo: https://github.com/NeerSpace/NeerCore.git
    id: Apply
    path: ../src/NeerCore.Api/Swagger/Filters/XLogoDocumentFilter.cs
    startLine: 14
  assemblies:
  - NeerCore.Api
  namespace: NeerCore.Api.Swagger.Filters
  syntax:
    content: public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
    parameters:
    - id: swaggerDoc
      type: OpenApiDocument
    - id: context
      type: DocumentFilterContext
    content.vb: Public Sub Apply(swaggerDoc As OpenApiDocument, context As DocumentFilterContext)
  overload: NeerCore.Api.Swagger.Filters.XLogoDocumentFilter.Apply*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: NeerCore.Api.Swagger.Filters
  commentId: N:NeerCore.Api.Swagger.Filters
  name: NeerCore.Api.Swagger.Filters
  nameWithType: NeerCore.Api.Swagger.Filters
  fullName: NeerCore.Api.Swagger.Filters
- uid: NeerCore.Api.Swagger.Filters.XLogoDocumentFilter.Apply*
  commentId: Overload:NeerCore.Api.Swagger.Filters.XLogoDocumentFilter.Apply
  name: Apply
  nameWithType: XLogoDocumentFilter.Apply
  fullName: NeerCore.Api.Swagger.Filters.XLogoDocumentFilter.Apply
- uid: OpenApiDocument
  isExternal: true
  name: OpenApiDocument
  nameWithType: OpenApiDocument
  fullName: OpenApiDocument
- uid: DocumentFilterContext
  isExternal: true
  name: DocumentFilterContext
  nameWithType: DocumentFilterContext
  fullName: DocumentFilterContext
