### YamlMime:ManagedReference
items:
- uid: NeerCore.Api.Extensions.WebApplicationExtensions
  commentId: T:NeerCore.Api.Extensions.WebApplicationExtensions
  id: WebApplicationExtensions
  parent: NeerCore.Api.Extensions
  children:
  - NeerCore.Api.Extensions.WebApplicationExtensions.ForceRedirect(WebApplication,System.String,System.String)
  langs:
  - csharp
  - vb
  name: WebApplicationExtensions
  nameWithType: WebApplicationExtensions
  fullName: NeerCore.Api.Extensions.WebApplicationExtensions
  type: Class
  source:
    remote:
      path: src/NeerCore.Api/Extensions/WebApplicationExtensions.cs
      branch: v2.0.0
      repo: https://github.com/NeerSpace/NeerCore.git
    id: WebApplicationExtensions
    path: ../src/NeerCore.Api/Extensions/WebApplicationExtensions.cs
    startLine: 4
  assemblies:
  - NeerCore.Api
  namespace: NeerCore.Api.Extensions
  syntax:
    content: 'public static class WebApplicationExtensions : object'
    content.vb: >-
      Public Module WebApplicationExtensions
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: NeerCore.Api.Extensions.WebApplicationExtensions.ForceRedirect(WebApplication,System.String,System.String)
  commentId: M:NeerCore.Api.Extensions.WebApplicationExtensions.ForceRedirect(WebApplication,System.String,System.String)
  id: ForceRedirect(WebApplication,System.String,System.String)
  isExtensionMethod: true
  parent: NeerCore.Api.Extensions.WebApplicationExtensions
  langs:
  - csharp
  - vb
  name: ForceRedirect(WebApplication, String, String)
  nameWithType: WebApplicationExtensions.ForceRedirect(WebApplication, String, String)
  fullName: NeerCore.Api.Extensions.WebApplicationExtensions.ForceRedirect(WebApplication, System.String, System.String)
  type: Method
  source:
    remote:
      path: src/NeerCore.Api/Extensions/WebApplicationExtensions.cs
      branch: v2.0.0
      repo: https://github.com/NeerSpace/NeerCore.git
    id: ForceRedirect
    path: ../src/NeerCore.Api/Extensions/WebApplicationExtensions.cs
    startLine: 12
  assemblies:
  - NeerCore.Api
  namespace: NeerCore.Api.Extensions
  summary: "\nRedirects requests from &apos;<code data-dev-comment-type=\"paramref\" class=\"paramref\">from</code>&apos; to &apos;<code data-dev-comment-type=\"paramref\" class=\"paramref\">to</code>&apos; URI.\n"
  example: []
  syntax:
    content: public static void ForceRedirect(this WebApplication app, string from, string to)
    parameters:
    - id: app
      type: WebApplication
      description: The web application used to configure the HTTP pipeline, and routes.
    - id: from
      type: System.String
      description: Source route.
    - id: to
      type: System.String
      description: Destination route.
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Sub ForceRedirect(app As WebApplication, from As String, to As String)
  overload: NeerCore.Api.Extensions.WebApplicationExtensions.ForceRedirect*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: NeerCore.Api.Extensions
  commentId: N:NeerCore.Api.Extensions
  name: NeerCore.Api.Extensions
  nameWithType: NeerCore.Api.Extensions
  fullName: NeerCore.Api.Extensions
- uid: NeerCore.Api.Extensions.WebApplicationExtensions.ForceRedirect*
  commentId: Overload:NeerCore.Api.Extensions.WebApplicationExtensions.ForceRedirect
  name: ForceRedirect
  nameWithType: WebApplicationExtensions.ForceRedirect
  fullName: NeerCore.Api.Extensions.WebApplicationExtensions.ForceRedirect
- uid: WebApplication
  commentId: '!:WebApplication'
  isExternal: true
  name: WebApplication
  nameWithType: WebApplication
  fullName: WebApplication
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
