### YamlMime:ManagedReference
items:
- uid: NeerCore.Api.Swagger.Filters.JsonPatchDocumentFilter
  commentId: T:NeerCore.Api.Swagger.Filters.JsonPatchDocumentFilter
  id: JsonPatchDocumentFilter
  parent: NeerCore.Api.Swagger.Filters
  children:
  - NeerCore.Api.Swagger.Filters.JsonPatchDocumentFilter.Apply(OpenApiDocument,DocumentFilterContext)
  langs:
  - csharp
  - vb
  name: JsonPatchDocumentFilter
  nameWithType: JsonPatchDocumentFilter
  fullName: NeerCore.Api.Swagger.Filters.JsonPatchDocumentFilter
  type: Class
  source:
    remote:
      path: src/NeerCore.Api/Swagger/Filters/JsonPatchDocumentFilter.cs
      branch: v2.0.0
      repo: https://github.com/NeerSpace/NeerCore.git
    id: JsonPatchDocumentFilter
    path: ../src/NeerCore.Api/Swagger/Filters/JsonPatchDocumentFilter.cs
    startLine: 14
  assemblies:
  - NeerCore.Api
  namespace: NeerCore.Api.Swagger.Filters
  summary: "\nSwagger document filter to hide redundant models from\n<see cref=\"!:Microsoft.AspNetCore.JsonPatch.JsonPatchDocument&lt;TModel>\"></see>.\n"
  example: []
  syntax:
    content: 'public sealed class JsonPatchDocumentFilter : IDocumentFilter'
    content.vb: >-
      Public NotInheritable Class JsonPatchDocumentFilter
          Inherits IDocumentFilter
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: NeerCore.Api.Swagger.Filters.JsonPatchDocumentFilter.Apply(OpenApiDocument,DocumentFilterContext)
  commentId: M:NeerCore.Api.Swagger.Filters.JsonPatchDocumentFilter.Apply(OpenApiDocument,DocumentFilterContext)
  id: Apply(OpenApiDocument,DocumentFilterContext)
  parent: NeerCore.Api.Swagger.Filters.JsonPatchDocumentFilter
  langs:
  - csharp
  - vb
  name: Apply(OpenApiDocument, DocumentFilterContext)
  nameWithType: JsonPatchDocumentFilter.Apply(OpenApiDocument, DocumentFilterContext)
  fullName: NeerCore.Api.Swagger.Filters.JsonPatchDocumentFilter.Apply(OpenApiDocument, DocumentFilterContext)
  type: Method
  source:
    remote:
      path: src/NeerCore.Api/Swagger/Filters/JsonPatchDocumentFilter.cs
      branch: v2.0.0
      repo: https://github.com/NeerSpace/NeerCore.git
    id: Apply
    path: ../src/NeerCore.Api/Swagger/Filters/JsonPatchDocumentFilter.cs
    startLine: 16
  assemblies:
  - NeerCore.Api
  namespace: NeerCore.Api.Swagger.Filters
  syntax:
    content: public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
    parameters:
    - id: swaggerDoc
      type: OpenApiDocument
    - id: context
      type: DocumentFilterContext
    content.vb: Public Sub Apply(swaggerDoc As OpenApiDocument, context As DocumentFilterContext)
  overload: NeerCore.Api.Swagger.Filters.JsonPatchDocumentFilter.Apply*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: NeerCore.Api.Swagger.Filters
  commentId: N:NeerCore.Api.Swagger.Filters
  name: NeerCore.Api.Swagger.Filters
  nameWithType: NeerCore.Api.Swagger.Filters
  fullName: NeerCore.Api.Swagger.Filters
- uid: NeerCore.Api.Swagger.Filters.JsonPatchDocumentFilter.Apply*
  commentId: Overload:NeerCore.Api.Swagger.Filters.JsonPatchDocumentFilter.Apply
  name: Apply
  nameWithType: JsonPatchDocumentFilter.Apply
  fullName: NeerCore.Api.Swagger.Filters.JsonPatchDocumentFilter.Apply
- uid: OpenApiDocument
  isExternal: true
  name: OpenApiDocument
  nameWithType: OpenApiDocument
  fullName: OpenApiDocument
- uid: DocumentFilterContext
  isExternal: true
  name: DocumentFilterContext
  nameWithType: DocumentFilterContext
  fullName: DocumentFilterContext
