### YamlMime:ManagedReference
items:
- uid: NeerCore.Api.Swagger.SwaggerSecurityOptions
  commentId: T:NeerCore.Api.Swagger.SwaggerSecurityOptions
  id: SwaggerSecurityOptions
  parent: NeerCore.Api.Swagger
  children:
  - NeerCore.Api.Swagger.SwaggerSecurityOptions.BearerFormat
  - NeerCore.Api.Swagger.SwaggerSecurityOptions.Description
  - NeerCore.Api.Swagger.SwaggerSecurityOptions.Enabled
  - NeerCore.Api.Swagger.SwaggerSecurityOptions.ParameterLocation
  - NeerCore.Api.Swagger.SwaggerSecurityOptions.ParameterName
  - NeerCore.Api.Swagger.SwaggerSecurityOptions.Scheme
  - NeerCore.Api.Swagger.SwaggerSecurityOptions.SchemeType
  langs:
  - csharp
  - vb
  name: SwaggerSecurityOptions
  nameWithType: SwaggerSecurityOptions
  fullName: NeerCore.Api.Swagger.SwaggerSecurityOptions
  type: Class
  source:
    remote:
      path: src/NeerCore.Api/Swagger/SwaggerConfigurationOptions.cs
      branch: v2.0.0
      repo: https://github.com/NeerSpace/NeerCore.git
    id: SwaggerSecurityOptions
    path: ../src/NeerCore.Api/Swagger/SwaggerConfigurationOptions.cs
    startLine: 19
  assemblies:
  - NeerCore.Api
  namespace: NeerCore.Api.Swagger
  syntax:
    content: 'public sealed class SwaggerSecurityOptions : object'
    content.vb: >-
      Public NotInheritable Class SwaggerSecurityOptions
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: NeerCore.Api.Swagger.SwaggerSecurityOptions.Enabled
  commentId: P:NeerCore.Api.Swagger.SwaggerSecurityOptions.Enabled
  id: Enabled
  parent: NeerCore.Api.Swagger.SwaggerSecurityOptions
  langs:
  - csharp
  - vb
  name: Enabled
  nameWithType: SwaggerSecurityOptions.Enabled
  fullName: NeerCore.Api.Swagger.SwaggerSecurityOptions.Enabled
  type: Property
  source:
    remote:
      path: src/NeerCore.Api/Swagger/SwaggerConfigurationOptions.cs
      branch: v2.0.0
      repo: https://github.com/NeerSpace/NeerCore.git
    id: Enabled
    path: ../src/NeerCore.Api/Swagger/SwaggerConfigurationOptions.cs
    startLine: 21
  assemblies:
  - NeerCore.Api
  namespace: NeerCore.Api.Swagger
  syntax:
    content: public bool Enabled { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property Enabled As Boolean
  overload: NeerCore.Api.Swagger.SwaggerSecurityOptions.Enabled*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: NeerCore.Api.Swagger.SwaggerSecurityOptions.Scheme
  commentId: P:NeerCore.Api.Swagger.SwaggerSecurityOptions.Scheme
  id: Scheme
  parent: NeerCore.Api.Swagger.SwaggerSecurityOptions
  langs:
  - csharp
  - vb
  name: Scheme
  nameWithType: SwaggerSecurityOptions.Scheme
  fullName: NeerCore.Api.Swagger.SwaggerSecurityOptions.Scheme
  type: Property
  source:
    remote:
      path: src/NeerCore.Api/Swagger/SwaggerConfigurationOptions.cs
      branch: v2.0.0
      repo: https://github.com/NeerSpace/NeerCore.git
    id: Scheme
    path: ../src/NeerCore.Api/Swagger/SwaggerConfigurationOptions.cs
    startLine: 22
  assemblies:
  - NeerCore.Api
  namespace: NeerCore.Api.Swagger
  syntax:
    content: public string Scheme { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Scheme As String
  overload: NeerCore.Api.Swagger.SwaggerSecurityOptions.Scheme*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: NeerCore.Api.Swagger.SwaggerSecurityOptions.SchemeType
  commentId: P:NeerCore.Api.Swagger.SwaggerSecurityOptions.SchemeType
  id: SchemeType
  parent: NeerCore.Api.Swagger.SwaggerSecurityOptions
  langs:
  - csharp
  - vb
  name: SchemeType
  nameWithType: SwaggerSecurityOptions.SchemeType
  fullName: NeerCore.Api.Swagger.SwaggerSecurityOptions.SchemeType
  type: Property
  source:
    remote:
      path: src/NeerCore.Api/Swagger/SwaggerConfigurationOptions.cs
      branch: v2.0.0
      repo: https://github.com/NeerSpace/NeerCore.git
    id: SchemeType
    path: ../src/NeerCore.Api/Swagger/SwaggerConfigurationOptions.cs
    startLine: 23
  assemblies:
  - NeerCore.Api
  namespace: NeerCore.Api.Swagger
  syntax:
    content: public SecuritySchemeType SchemeType { get; set; }
    parameters: []
    return:
      type: SecuritySchemeType
    content.vb: Public Property SchemeType As SecuritySchemeType
  overload: NeerCore.Api.Swagger.SwaggerSecurityOptions.SchemeType*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: NeerCore.Api.Swagger.SwaggerSecurityOptions.BearerFormat
  commentId: P:NeerCore.Api.Swagger.SwaggerSecurityOptions.BearerFormat
  id: BearerFormat
  parent: NeerCore.Api.Swagger.SwaggerSecurityOptions
  langs:
  - csharp
  - vb
  name: BearerFormat
  nameWithType: SwaggerSecurityOptions.BearerFormat
  fullName: NeerCore.Api.Swagger.SwaggerSecurityOptions.BearerFormat
  type: Property
  source:
    remote:
      path: src/NeerCore.Api/Swagger/SwaggerConfigurationOptions.cs
      branch: v2.0.0
      repo: https://github.com/NeerSpace/NeerCore.git
    id: BearerFormat
    path: ../src/NeerCore.Api/Swagger/SwaggerConfigurationOptions.cs
    startLine: 24
  assemblies:
  - NeerCore.Api
  namespace: NeerCore.Api.Swagger
  syntax:
    content: public string BearerFormat { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property BearerFormat As String
  overload: NeerCore.Api.Swagger.SwaggerSecurityOptions.BearerFormat*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: NeerCore.Api.Swagger.SwaggerSecurityOptions.ParameterName
  commentId: P:NeerCore.Api.Swagger.SwaggerSecurityOptions.ParameterName
  id: ParameterName
  parent: NeerCore.Api.Swagger.SwaggerSecurityOptions
  langs:
  - csharp
  - vb
  name: ParameterName
  nameWithType: SwaggerSecurityOptions.ParameterName
  fullName: NeerCore.Api.Swagger.SwaggerSecurityOptions.ParameterName
  type: Property
  source:
    remote:
      path: src/NeerCore.Api/Swagger/SwaggerConfigurationOptions.cs
      branch: v2.0.0
      repo: https://github.com/NeerSpace/NeerCore.git
    id: ParameterName
    path: ../src/NeerCore.Api/Swagger/SwaggerConfigurationOptions.cs
    startLine: 25
  assemblies:
  - NeerCore.Api
  namespace: NeerCore.Api.Swagger
  syntax:
    content: public string ParameterName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ParameterName As String
  overload: NeerCore.Api.Swagger.SwaggerSecurityOptions.ParameterName*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: NeerCore.Api.Swagger.SwaggerSecurityOptions.ParameterLocation
  commentId: P:NeerCore.Api.Swagger.SwaggerSecurityOptions.ParameterLocation
  id: ParameterLocation
  parent: NeerCore.Api.Swagger.SwaggerSecurityOptions
  langs:
  - csharp
  - vb
  name: ParameterLocation
  nameWithType: SwaggerSecurityOptions.ParameterLocation
  fullName: NeerCore.Api.Swagger.SwaggerSecurityOptions.ParameterLocation
  type: Property
  source:
    remote:
      path: src/NeerCore.Api/Swagger/SwaggerConfigurationOptions.cs
      branch: v2.0.0
      repo: https://github.com/NeerSpace/NeerCore.git
    id: ParameterLocation
    path: ../src/NeerCore.Api/Swagger/SwaggerConfigurationOptions.cs
    startLine: 26
  assemblies:
  - NeerCore.Api
  namespace: NeerCore.Api.Swagger
  syntax:
    content: public ParameterLocation ParameterLocation { get; set; }
    parameters: []
    return:
      type: ParameterLocation
    content.vb: Public Property ParameterLocation As ParameterLocation
  overload: NeerCore.Api.Swagger.SwaggerSecurityOptions.ParameterLocation*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: NeerCore.Api.Swagger.SwaggerSecurityOptions.Description
  commentId: P:NeerCore.Api.Swagger.SwaggerSecurityOptions.Description
  id: Description
  parent: NeerCore.Api.Swagger.SwaggerSecurityOptions
  langs:
  - csharp
  - vb
  name: Description
  nameWithType: SwaggerSecurityOptions.Description
  fullName: NeerCore.Api.Swagger.SwaggerSecurityOptions.Description
  type: Property
  source:
    remote:
      path: src/NeerCore.Api/Swagger/SwaggerConfigurationOptions.cs
      branch: v2.0.0
      repo: https://github.com/NeerSpace/NeerCore.git
    id: Description
    path: ../src/NeerCore.Api/Swagger/SwaggerConfigurationOptions.cs
    startLine: 27
  assemblies:
  - NeerCore.Api
  namespace: NeerCore.Api.Swagger
  syntax:
    content: public string Description { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Description As String
  overload: NeerCore.Api.Swagger.SwaggerSecurityOptions.Description*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: NeerCore.Api.Swagger
  commentId: N:NeerCore.Api.Swagger
  name: NeerCore.Api.Swagger
  nameWithType: NeerCore.Api.Swagger
  fullName: NeerCore.Api.Swagger
- uid: NeerCore.Api.Swagger.SwaggerSecurityOptions.Enabled*
  commentId: Overload:NeerCore.Api.Swagger.SwaggerSecurityOptions.Enabled
  name: Enabled
  nameWithType: SwaggerSecurityOptions.Enabled
  fullName: NeerCore.Api.Swagger.SwaggerSecurityOptions.Enabled
- uid: System.Boolean
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: NeerCore.Api.Swagger.SwaggerSecurityOptions.Scheme*
  commentId: Overload:NeerCore.Api.Swagger.SwaggerSecurityOptions.Scheme
  name: Scheme
  nameWithType: SwaggerSecurityOptions.Scheme
  fullName: NeerCore.Api.Swagger.SwaggerSecurityOptions.Scheme
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: NeerCore.Api.Swagger.SwaggerSecurityOptions.SchemeType*
  commentId: Overload:NeerCore.Api.Swagger.SwaggerSecurityOptions.SchemeType
  name: SchemeType
  nameWithType: SwaggerSecurityOptions.SchemeType
  fullName: NeerCore.Api.Swagger.SwaggerSecurityOptions.SchemeType
- uid: SecuritySchemeType
  commentId: '!:SecuritySchemeType'
  isExternal: true
  name: SecuritySchemeType
  nameWithType: SecuritySchemeType
  fullName: SecuritySchemeType
- uid: NeerCore.Api.Swagger.SwaggerSecurityOptions.BearerFormat*
  commentId: Overload:NeerCore.Api.Swagger.SwaggerSecurityOptions.BearerFormat
  name: BearerFormat
  nameWithType: SwaggerSecurityOptions.BearerFormat
  fullName: NeerCore.Api.Swagger.SwaggerSecurityOptions.BearerFormat
- uid: NeerCore.Api.Swagger.SwaggerSecurityOptions.ParameterName*
  commentId: Overload:NeerCore.Api.Swagger.SwaggerSecurityOptions.ParameterName
  name: ParameterName
  nameWithType: SwaggerSecurityOptions.ParameterName
  fullName: NeerCore.Api.Swagger.SwaggerSecurityOptions.ParameterName
- uid: NeerCore.Api.Swagger.SwaggerSecurityOptions.ParameterLocation*
  commentId: Overload:NeerCore.Api.Swagger.SwaggerSecurityOptions.ParameterLocation
  name: ParameterLocation
  nameWithType: SwaggerSecurityOptions.ParameterLocation
  fullName: NeerCore.Api.Swagger.SwaggerSecurityOptions.ParameterLocation
- uid: ParameterLocation
  commentId: '!:ParameterLocation'
  isExternal: true
  name: ParameterLocation
  nameWithType: ParameterLocation
  fullName: ParameterLocation
- uid: NeerCore.Api.Swagger.SwaggerSecurityOptions.Description*
  commentId: Overload:NeerCore.Api.Swagger.SwaggerSecurityOptions.Description
  name: Description
  nameWithType: SwaggerSecurityOptions.Description
  fullName: NeerCore.Api.Swagger.SwaggerSecurityOptions.Description
