### YamlMime:ManagedReference
items:
- uid: NeerCore.Api.Swagger.Filters
  commentId: N:NeerCore.Api.Swagger.Filters
  id: NeerCore.Api.Swagger.Filters
  children:
  - NeerCore.Api.Swagger.Filters.AuthorizeCheckOperationFilter
  - NeerCore.Api.Swagger.Filters.JsonPatchDocumentFilter
  - NeerCore.Api.Swagger.Filters.XLogoDocumentFilter
  langs:
  - csharp
  - vb
  name: NeerCore.Api.Swagger.Filters
  nameWithType: NeerCore.Api.Swagger.Filters
  fullName: NeerCore.Api.Swagger.Filters
  type: Namespace
  assemblies:
  - NeerCore.Api
references:
- uid: NeerCore.Api.Swagger.Filters.AuthorizeCheckOperationFilter
  commentId: T:NeerCore.Api.Swagger.Filters.AuthorizeCheckOperationFilter
  name: AuthorizeCheckOperationFilter
  nameWithType: AuthorizeCheckOperationFilter
  fullName: NeerCore.Api.Swagger.Filters.AuthorizeCheckOperationFilter
- uid: NeerCore.Api.Swagger.Filters.JsonPatchDocumentFilter
  commentId: T:NeerCore.Api.Swagger.Filters.JsonPatchDocumentFilter
  name: JsonPatchDocumentFilter
  nameWithType: JsonPatchDocumentFilter
  fullName: NeerCore.Api.Swagger.Filters.JsonPatchDocumentFilter
- uid: NeerCore.Api.Swagger.Filters.XLogoDocumentFilter
  commentId: T:NeerCore.Api.Swagger.Filters.XLogoDocumentFilter
  name: XLogoDocumentFilter
  nameWithType: XLogoDocumentFilter
  fullName: NeerCore.Api.Swagger.Filters.XLogoDocumentFilter
