### YamlMime:ManagedReference
items:
- uid: NeerCore.Api.Swagger.Extensions
  commentId: N:NeerCore.Api.Swagger.Extensions
  id: NeerCore.Api.Swagger.Extensions
  children:
  - NeerCore.Api.Swagger.Extensions.SwaggerExtensions
  langs:
  - csharp
  - vb
  name: NeerCore.Api.Swagger.Extensions
  nameWithType: NeerCore.Api.Swagger.Extensions
  fullName: NeerCore.Api.Swagger.Extensions
  type: Namespace
  assemblies:
  - NeerCore.Api
references:
- uid: NeerCore.Api.Swagger.Extensions.SwaggerExtensions
  commentId: T:NeerCore.Api.Swagger.Extensions.SwaggerExtensions
  name: SwaggerExtensions
  nameWithType: SwaggerExtensions
  fullName: NeerCore.Api.Swagger.Extensions.SwaggerExtensions
