site_name: NeerCore
site_url: https://github.com/NeerSpace/NeerCore-Docs
site_author: jurilents
repo_url: https://github.com/NeerSpace/NeerCore
docs_dir: src

theme:
  name: material
  #  highlightjs: true
  #  max_toc_depth: 2
  favicon: assets/favicon.png
  logo: assets/favicon.png

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: black
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - admonition
  - markdown.extensions.toc:
      permalink: true

extra:
  version:
    default: stable
