name: Publish Docs

on:
  push:
    branches:
      - master
      - v2.0.0
    paths:
      - src/**
      - docs/**
      - .github/workflows/docs.yml

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  generate-docs:

    runs-on: windows-latest

    steps:
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Setup DocFX
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docfx

      - name: DocFX Build
        working-directory: docs
        run: docfx ./docfx.json
        continue-on-error: false

      - name: Publish GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: documentation
          publish_dir: docs/_site
          force_orphan: true
